### ISSUE TITLE
Player Turns

### ISSUE THREAD

**Issue by CollinSchneider** [CollinSchneider/gameNumberOne#1]
The first move for each player functions as expected, however after that the player turns become out of sync. The computer attacks multiple times in a row, and the player sends multiple attacks after one click as well. The 'currentPlayer' variable must not be adding by one after each move somewhere in my code but I can't find it.
I know I have a lot of extra code, I'm still trying to weed through it all to see what should and should not be there for the game to function as expected.

**Comment by Avizacherman** [comment]
Followed up in person, closed until further work done.
