### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Avizacherman** [CollinSchneider/gameNumberOne#2]
Collin,

Great job on this game. It was fun to battle with pokemans. I also like seeing that you're thinking ahead of how you can continue working on this project. 

In terms of your code, I like what you have. I think you clearly have the logic down. One thing I would love to see you do is refactor to follow more Object Oriented paradigms. For example, creating a Pikachu constructor and giving it moves. How do you think you would do this?

**Comment by ajhofferber** [comment]
Hey Collin!

Really great work on this first project! I like that you were able to come up with this idea based on Pokemon battles and think through how you would write that logic with JavaScript. I also think it is great that you know the kinds of things you could imagine adding to your project in future versions.

I am glad to see that you've taken a stab at adding information to your readme.md. But perhaps you could add some headers or things to make the page a bit more interesting. Here is a link to some markdown documentation, just for reference: https://help.github.com/articles/markdown-basics/

Again, overall, great work!  

Score: 3 (refer to project markdown for scoring)

Ash
